package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADDED_TRAINING_SHG_MEMBER_DATA".
*/
public class AddedTrainingShgMemberDataDao extends AbstractDao<AddedTrainingShgMemberData, Long> {

    public static final String TABLENAME = "ADDED_TRAINING_SHG_MEMBER_DATA";

    /**
     * Properties of entity AddedTrainingShgMemberData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrainingId = new Property(1, String.class, "trainingId", false, "TRAINING_ID");
        public final static Property ShgCode = new Property(2, String.class, "shgCode", false, "SHG_CODE");
        public final static Property ShgMemberCode = new Property(3, String.class, "shgMemberCode", false, "SHG_MEMBER_CODE");
    }


    public AddedTrainingShgMemberDataDao(DaoConfig config) {
        super(config);
    }
    
    public AddedTrainingShgMemberDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADDED_TRAINING_SHG_MEMBER_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRAINING_ID\" TEXT," + // 1: trainingId
                "\"SHG_CODE\" TEXT," + // 2: shgCode
                "\"SHG_MEMBER_CODE\" TEXT);"); // 3: shgMemberCode
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADDED_TRAINING_SHG_MEMBER_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AddedTrainingShgMemberData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String shgMemberCode = entity.getShgMemberCode();
        if (shgMemberCode != null) {
            stmt.bindString(4, shgMemberCode);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AddedTrainingShgMemberData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String shgMemberCode = entity.getShgMemberCode();
        if (shgMemberCode != null) {
            stmt.bindString(4, shgMemberCode);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AddedTrainingShgMemberData readEntity(Cursor cursor, int offset) {
        AddedTrainingShgMemberData entity = new AddedTrainingShgMemberData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // trainingId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // shgMemberCode
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AddedTrainingShgMemberData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrainingId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setShgMemberCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AddedTrainingShgMemberData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AddedTrainingShgMemberData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AddedTrainingShgMemberData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
