package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADDED_TRAINING_SHG_DATA".
*/
public class AddedTrainingShgDataDao extends AbstractDao<AddedTrainingShgData, Long> {

    public static final String TABLENAME = "ADDED_TRAINING_SHG_DATA";

    /**
     * Properties of entity AddedTrainingShgData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrainingId = new Property(1, String.class, "trainingId", false, "TRAINING_ID");
        public final static Property ShgCode = new Property(2, String.class, "shgCode", false, "SHG_CODE");
        public final static Property EvaluationStatusForShg = new Property(3, String.class, "evaluationStatusForShg", false, "EVALUATION_STATUS_FOR_SHG");
        public final static Property ShgMemberInTraining = new Property(4, String.class, "shgMemberInTraining", false, "SHG_MEMBER_IN_TRAINING");
    }


    public AddedTrainingShgDataDao(DaoConfig config) {
        super(config);
    }
    
    public AddedTrainingShgDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADDED_TRAINING_SHG_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRAINING_ID\" TEXT," + // 1: trainingId
                "\"SHG_CODE\" TEXT," + // 2: shgCode
                "\"EVALUATION_STATUS_FOR_SHG\" TEXT," + // 3: evaluationStatusForShg
                "\"SHG_MEMBER_IN_TRAINING\" TEXT);"); // 4: shgMemberInTraining
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADDED_TRAINING_SHG_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AddedTrainingShgData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String evaluationStatusForShg = entity.getEvaluationStatusForShg();
        if (evaluationStatusForShg != null) {
            stmt.bindString(4, evaluationStatusForShg);
        }
 
        String shgMemberInTraining = entity.getShgMemberInTraining();
        if (shgMemberInTraining != null) {
            stmt.bindString(5, shgMemberInTraining);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AddedTrainingShgData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String evaluationStatusForShg = entity.getEvaluationStatusForShg();
        if (evaluationStatusForShg != null) {
            stmt.bindString(4, evaluationStatusForShg);
        }
 
        String shgMemberInTraining = entity.getShgMemberInTraining();
        if (shgMemberInTraining != null) {
            stmt.bindString(5, shgMemberInTraining);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AddedTrainingShgData readEntity(Cursor cursor, int offset) {
        AddedTrainingShgData entity = new AddedTrainingShgData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // trainingId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // evaluationStatusForShg
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // shgMemberInTraining
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AddedTrainingShgData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrainingId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEvaluationStatusForShg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setShgMemberInTraining(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AddedTrainingShgData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AddedTrainingShgData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AddedTrainingShgData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
