package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADDED_TRAINING_SHG_MODULE_DATA".
*/
public class AddedTrainingShgModuleDataDao extends AbstractDao<AddedTrainingShgModuleData, Long> {

    public static final String TABLENAME = "ADDED_TRAINING_SHG_MODULE_DATA";

    /**
     * Properties of entity AddedTrainingShgModuleData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrainingId = new Property(1, String.class, "trainingId", false, "TRAINING_ID");
        public final static Property ShgCode = new Property(2, String.class, "shgCode", false, "SHG_CODE");
        public final static Property ModuleId = new Property(3, String.class, "moduleId", false, "MODULE_ID");
        public final static Property ModuleName = new Property(4, String.class, "moduleName", false, "MODULE_NAME");
        public final static Property ModuleCount = new Property(5, String.class, "moduleCount", false, "MODULE_COUNT");
    }


    public AddedTrainingShgModuleDataDao(DaoConfig config) {
        super(config);
    }
    
    public AddedTrainingShgModuleDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADDED_TRAINING_SHG_MODULE_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRAINING_ID\" TEXT," + // 1: trainingId
                "\"SHG_CODE\" TEXT," + // 2: shgCode
                "\"MODULE_ID\" TEXT," + // 3: moduleId
                "\"MODULE_NAME\" TEXT," + // 4: moduleName
                "\"MODULE_COUNT\" TEXT);"); // 5: moduleCount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADDED_TRAINING_SHG_MODULE_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AddedTrainingShgModuleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String moduleId = entity.getModuleId();
        if (moduleId != null) {
            stmt.bindString(4, moduleId);
        }
 
        String moduleName = entity.getModuleName();
        if (moduleName != null) {
            stmt.bindString(5, moduleName);
        }
 
        String moduleCount = entity.getModuleCount();
        if (moduleCount != null) {
            stmt.bindString(6, moduleCount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AddedTrainingShgModuleData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String moduleId = entity.getModuleId();
        if (moduleId != null) {
            stmt.bindString(4, moduleId);
        }
 
        String moduleName = entity.getModuleName();
        if (moduleName != null) {
            stmt.bindString(5, moduleName);
        }
 
        String moduleCount = entity.getModuleCount();
        if (moduleCount != null) {
            stmt.bindString(6, moduleCount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AddedTrainingShgModuleData readEntity(Cursor cursor, int offset) {
        AddedTrainingShgModuleData entity = new AddedTrainingShgModuleData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // trainingId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // moduleId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // moduleName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // moduleCount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AddedTrainingShgModuleData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrainingId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setModuleId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setModuleName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setModuleCount(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AddedTrainingShgModuleData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AddedTrainingShgModuleData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AddedTrainingShgModuleData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
