package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASELINE_SYNC_DATA".
*/
public class BaselineSyncDataDao extends AbstractDao<BaselineSyncData, Long> {

    public static final String TABLENAME = "BASELINE_SYNC_DATA";

    /**
     * Properties of entity BaselineSyncData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShgCode = new Property(1, String.class, "shgCode", false, "SHG_CODE");
        public final static Property BasLineStatus = new Property(2, String.class, "basLineStatus", false, "BAS_LINE_STATUS");
        public final static Property EnterMemberValue = new Property(3, String.class, "enterMemberValue", false, "ENTER_MEMBER_VALUE");
        public final static Property VillageCode = new Property(4, String.class, "villageCode", false, "VILLAGE_CODE");
        public final static Property UserSelectedDate = new Property(5, String.class, "userSelectedDate", false, "USER_SELECTED_DATE");
        public final static Property TodayDate = new Property(6, String.class, "todayDate", false, "TODAY_DATE");
    }


    public BaselineSyncDataDao(DaoConfig config) {
        super(config);
    }
    
    public BaselineSyncDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASELINE_SYNC_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHG_CODE\" TEXT," + // 1: shgCode
                "\"BAS_LINE_STATUS\" TEXT," + // 2: basLineStatus
                "\"ENTER_MEMBER_VALUE\" TEXT," + // 3: enterMemberValue
                "\"VILLAGE_CODE\" TEXT," + // 4: villageCode
                "\"USER_SELECTED_DATE\" TEXT," + // 5: userSelectedDate
                "\"TODAY_DATE\" TEXT);"); // 6: todayDate
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASELINE_SYNC_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaselineSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String basLineStatus = entity.getBasLineStatus();
        if (basLineStatus != null) {
            stmt.bindString(3, basLineStatus);
        }
 
        String enterMemberValue = entity.getEnterMemberValue();
        if (enterMemberValue != null) {
            stmt.bindString(4, enterMemberValue);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(5, villageCode);
        }
 
        String userSelectedDate = entity.getUserSelectedDate();
        if (userSelectedDate != null) {
            stmt.bindString(6, userSelectedDate);
        }
 
        String todayDate = entity.getTodayDate();
        if (todayDate != null) {
            stmt.bindString(7, todayDate);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaselineSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String basLineStatus = entity.getBasLineStatus();
        if (basLineStatus != null) {
            stmt.bindString(3, basLineStatus);
        }
 
        String enterMemberValue = entity.getEnterMemberValue();
        if (enterMemberValue != null) {
            stmt.bindString(4, enterMemberValue);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(5, villageCode);
        }
 
        String userSelectedDate = entity.getUserSelectedDate();
        if (userSelectedDate != null) {
            stmt.bindString(6, userSelectedDate);
        }
 
        String todayDate = entity.getTodayDate();
        if (todayDate != null) {
            stmt.bindString(7, todayDate);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BaselineSyncData readEntity(Cursor cursor, int offset) {
        BaselineSyncData entity = new BaselineSyncData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shgCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // basLineStatus
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // enterMemberValue
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // villageCode
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // userSelectedDate
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // todayDate
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaselineSyncData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShgCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBasLineStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setEnterMemberValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setVillageCode(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUserSelectedDate(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTodayDate(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BaselineSyncData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BaselineSyncData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaselineSyncData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
