package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASLINE_QUESTION_SYNC_DATA".
*/
public class BaslineQuestionSyncDataDao extends AbstractDao<BaslineQuestionSyncData, Long> {

    public static final String TABLENAME = "BASLINE_QUESTION_SYNC_DATA";

    /**
     * Properties of entity BaslineQuestionSyncData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShgCode = new Property(1, String.class, "shgCode", false, "SHG_CODE");
        public final static Property BaslineStatus = new Property(2, String.class, "baslineStatus", false, "BASLINE_STATUS");
        public final static Property QuestionId = new Property(3, String.class, "questionId", false, "QUESTION_ID");
        public final static Property AnswerForQuestion = new Property(4, String.class, "answerForQuestion", false, "ANSWER_FOR_QUESTION");
    }


    public BaslineQuestionSyncDataDao(DaoConfig config) {
        super(config);
    }
    
    public BaslineQuestionSyncDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASLINE_QUESTION_SYNC_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHG_CODE\" TEXT," + // 1: shgCode
                "\"BASLINE_STATUS\" TEXT," + // 2: baslineStatus
                "\"QUESTION_ID\" TEXT," + // 3: questionId
                "\"ANSWER_FOR_QUESTION\" TEXT);"); // 4: answerForQuestion
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASLINE_QUESTION_SYNC_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BaslineQuestionSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String baslineStatus = entity.getBaslineStatus();
        if (baslineStatus != null) {
            stmt.bindString(3, baslineStatus);
        }
 
        String questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindString(4, questionId);
        }
 
        String answerForQuestion = entity.getAnswerForQuestion();
        if (answerForQuestion != null) {
            stmt.bindString(5, answerForQuestion);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BaslineQuestionSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String baslineStatus = entity.getBaslineStatus();
        if (baslineStatus != null) {
            stmt.bindString(3, baslineStatus);
        }
 
        String questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindString(4, questionId);
        }
 
        String answerForQuestion = entity.getAnswerForQuestion();
        if (answerForQuestion != null) {
            stmt.bindString(5, answerForQuestion);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BaslineQuestionSyncData readEntity(Cursor cursor, int offset) {
        BaslineQuestionSyncData entity = new BaslineQuestionSyncData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shgCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // baslineStatus
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // questionId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // answerForQuestion
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BaslineQuestionSyncData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShgCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBaslineStatus(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQuestionId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAnswerForQuestion(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BaslineQuestionSyncData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BaslineQuestionSyncData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BaslineQuestionSyncData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
