package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLOCK_DATA".
*/
public class BlockDataDao extends AbstractDao<BlockData, Void> {

    public static final String TABLENAME = "BLOCK_DATA";

    /**
     * Properties of entity BlockData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BlockCode = new Property(0, String.class, "blockCode", false, "BLOCK_CODE");
        public final static Property BlockName = new Property(1, String.class, "blockName", false, "BLOCK_NAME");
    }


    public BlockDataDao(DaoConfig config) {
        super(config);
    }
    
    public BlockDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLOCK_DATA\" (" + //
                "\"BLOCK_CODE\" TEXT," + // 0: blockCode
                "\"BLOCK_NAME\" TEXT);"); // 1: blockName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLOCK_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlockData entity) {
        stmt.clearBindings();
 
        String blockCode = entity.getBlockCode();
        if (blockCode != null) {
            stmt.bindString(1, blockCode);
        }
 
        String blockName = entity.getBlockName();
        if (blockName != null) {
            stmt.bindString(2, blockName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlockData entity) {
        stmt.clearBindings();
 
        String blockCode = entity.getBlockCode();
        if (blockCode != null) {
            stmt.bindString(1, blockCode);
        }
 
        String blockName = entity.getBlockName();
        if (blockName != null) {
            stmt.bindString(2, blockName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public BlockData readEntity(Cursor cursor, int offset) {
        BlockData entity = new BlockData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // blockCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // blockName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlockData entity, int offset) {
        entity.setBlockCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setBlockName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(BlockData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(BlockData entity) {
        return null;
    }

    @Override
    public boolean hasKey(BlockData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
