package com.shaksham.model.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shaksham.model.database.AddedTrainingShgData;
import com.shaksham.model.database.AddedTrainingShgMemberData;
import com.shaksham.model.database.AddedTrainingShgModuleData;
import com.shaksham.model.database.AddedTrainingsData;
import com.shaksham.model.database.BaselineSyncData;
import com.shaksham.model.database.BaslineQuestionSyncData;
import com.shaksham.model.database.BlockData;
import com.shaksham.model.database.BlockLevelData;
import com.shaksham.model.database.EvaluationMasterLocationData;
import com.shaksham.model.database.EvaluationMasterShgData;
import com.shaksham.model.database.EvaluationMasterTrainingData;
import com.shaksham.model.database.EvaluationSyncData;
import com.shaksham.model.database.EvaluationSyncQuestionData;
import com.shaksham.model.database.EvaluationSyncShgData;
import com.shaksham.model.database.GpData;
import com.shaksham.model.database.LoginInfo;
import com.shaksham.model.database.ModuleData;
import com.shaksham.model.database.QuestionInfoDetail;
import com.shaksham.model.database.ShgData;
import com.shaksham.model.database.ShgMemberData;
import com.shaksham.model.database.ShgModuleData;
import com.shaksham.model.database.TitleInfoDetail;
import com.shaksham.model.database.TrainingInfoData;
import com.shaksham.model.database.TrainingLocationInfo;
import com.shaksham.model.database.TrainingModuleInfo;
import com.shaksham.model.database.TrainingShgAndMemberData;
import com.shaksham.model.database.ViewReportData;
import com.shaksham.model.database.ViewReportModuleData;
import com.shaksham.model.database.ViewReportMonthData;
import com.shaksham.model.database.ViewReportTrainingData;
import com.shaksham.model.database.VillageData;
import com.shaksham.model.database.WebRequestData;

import com.shaksham.model.database.AddedTrainingShgDataDao;
import com.shaksham.model.database.AddedTrainingShgMemberDataDao;
import com.shaksham.model.database.AddedTrainingShgModuleDataDao;
import com.shaksham.model.database.AddedTrainingsDataDao;
import com.shaksham.model.database.BaselineSyncDataDao;
import com.shaksham.model.database.BaslineQuestionSyncDataDao;
import com.shaksham.model.database.BlockDataDao;
import com.shaksham.model.database.BlockLevelDataDao;
import com.shaksham.model.database.EvaluationMasterLocationDataDao;
import com.shaksham.model.database.EvaluationMasterShgDataDao;
import com.shaksham.model.database.EvaluationMasterTrainingDataDao;
import com.shaksham.model.database.EvaluationSyncDataDao;
import com.shaksham.model.database.EvaluationSyncQuestionDataDao;
import com.shaksham.model.database.EvaluationSyncShgDataDao;
import com.shaksham.model.database.GpDataDao;
import com.shaksham.model.database.LoginInfoDao;
import com.shaksham.model.database.ModuleDataDao;
import com.shaksham.model.database.QuestionInfoDetailDao;
import com.shaksham.model.database.ShgDataDao;
import com.shaksham.model.database.ShgMemberDataDao;
import com.shaksham.model.database.ShgModuleDataDao;
import com.shaksham.model.database.TitleInfoDetailDao;
import com.shaksham.model.database.TrainingInfoDataDao;
import com.shaksham.model.database.TrainingLocationInfoDao;
import com.shaksham.model.database.TrainingModuleInfoDao;
import com.shaksham.model.database.TrainingShgAndMemberDataDao;
import com.shaksham.model.database.ViewReportDataDao;
import com.shaksham.model.database.ViewReportModuleDataDao;
import com.shaksham.model.database.ViewReportMonthDataDao;
import com.shaksham.model.database.ViewReportTrainingDataDao;
import com.shaksham.model.database.VillageDataDao;
import com.shaksham.model.database.WebRequestDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addedTrainingShgDataDaoConfig;
    private final DaoConfig addedTrainingShgMemberDataDaoConfig;
    private final DaoConfig addedTrainingShgModuleDataDaoConfig;
    private final DaoConfig addedTrainingsDataDaoConfig;
    private final DaoConfig baselineSyncDataDaoConfig;
    private final DaoConfig baslineQuestionSyncDataDaoConfig;
    private final DaoConfig blockDataDaoConfig;
    private final DaoConfig blockLevelDataDaoConfig;
    private final DaoConfig evaluationMasterLocationDataDaoConfig;
    private final DaoConfig evaluationMasterShgDataDaoConfig;
    private final DaoConfig evaluationMasterTrainingDataDaoConfig;
    private final DaoConfig evaluationSyncDataDaoConfig;
    private final DaoConfig evaluationSyncQuestionDataDaoConfig;
    private final DaoConfig evaluationSyncShgDataDaoConfig;
    private final DaoConfig gpDataDaoConfig;
    private final DaoConfig loginInfoDaoConfig;
    private final DaoConfig moduleDataDaoConfig;
    private final DaoConfig questionInfoDetailDaoConfig;
    private final DaoConfig shgDataDaoConfig;
    private final DaoConfig shgMemberDataDaoConfig;
    private final DaoConfig shgModuleDataDaoConfig;
    private final DaoConfig titleInfoDetailDaoConfig;
    private final DaoConfig trainingInfoDataDaoConfig;
    private final DaoConfig trainingLocationInfoDaoConfig;
    private final DaoConfig trainingModuleInfoDaoConfig;
    private final DaoConfig trainingShgAndMemberDataDaoConfig;
    private final DaoConfig viewReportDataDaoConfig;
    private final DaoConfig viewReportModuleDataDaoConfig;
    private final DaoConfig viewReportMonthDataDaoConfig;
    private final DaoConfig viewReportTrainingDataDaoConfig;
    private final DaoConfig villageDataDaoConfig;
    private final DaoConfig webRequestDataDaoConfig;

    private final AddedTrainingShgDataDao addedTrainingShgDataDao;
    private final AddedTrainingShgMemberDataDao addedTrainingShgMemberDataDao;
    private final AddedTrainingShgModuleDataDao addedTrainingShgModuleDataDao;
    private final AddedTrainingsDataDao addedTrainingsDataDao;
    private final BaselineSyncDataDao baselineSyncDataDao;
    private final BaslineQuestionSyncDataDao baslineQuestionSyncDataDao;
    private final BlockDataDao blockDataDao;
    private final BlockLevelDataDao blockLevelDataDao;
    private final EvaluationMasterLocationDataDao evaluationMasterLocationDataDao;
    private final EvaluationMasterShgDataDao evaluationMasterShgDataDao;
    private final EvaluationMasterTrainingDataDao evaluationMasterTrainingDataDao;
    private final EvaluationSyncDataDao evaluationSyncDataDao;
    private final EvaluationSyncQuestionDataDao evaluationSyncQuestionDataDao;
    private final EvaluationSyncShgDataDao evaluationSyncShgDataDao;
    private final GpDataDao gpDataDao;
    private final LoginInfoDao loginInfoDao;
    private final ModuleDataDao moduleDataDao;
    private final QuestionInfoDetailDao questionInfoDetailDao;
    private final ShgDataDao shgDataDao;
    private final ShgMemberDataDao shgMemberDataDao;
    private final ShgModuleDataDao shgModuleDataDao;
    private final TitleInfoDetailDao titleInfoDetailDao;
    private final TrainingInfoDataDao trainingInfoDataDao;
    private final TrainingLocationInfoDao trainingLocationInfoDao;
    private final TrainingModuleInfoDao trainingModuleInfoDao;
    private final TrainingShgAndMemberDataDao trainingShgAndMemberDataDao;
    private final ViewReportDataDao viewReportDataDao;
    private final ViewReportModuleDataDao viewReportModuleDataDao;
    private final ViewReportMonthDataDao viewReportMonthDataDao;
    private final ViewReportTrainingDataDao viewReportTrainingDataDao;
    private final VillageDataDao villageDataDao;
    private final WebRequestDataDao webRequestDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addedTrainingShgDataDaoConfig = daoConfigMap.get(AddedTrainingShgDataDao.class).clone();
        addedTrainingShgDataDaoConfig.initIdentityScope(type);

        addedTrainingShgMemberDataDaoConfig = daoConfigMap.get(AddedTrainingShgMemberDataDao.class).clone();
        addedTrainingShgMemberDataDaoConfig.initIdentityScope(type);

        addedTrainingShgModuleDataDaoConfig = daoConfigMap.get(AddedTrainingShgModuleDataDao.class).clone();
        addedTrainingShgModuleDataDaoConfig.initIdentityScope(type);

        addedTrainingsDataDaoConfig = daoConfigMap.get(AddedTrainingsDataDao.class).clone();
        addedTrainingsDataDaoConfig.initIdentityScope(type);

        baselineSyncDataDaoConfig = daoConfigMap.get(BaselineSyncDataDao.class).clone();
        baselineSyncDataDaoConfig.initIdentityScope(type);

        baslineQuestionSyncDataDaoConfig = daoConfigMap.get(BaslineQuestionSyncDataDao.class).clone();
        baslineQuestionSyncDataDaoConfig.initIdentityScope(type);

        blockDataDaoConfig = daoConfigMap.get(BlockDataDao.class).clone();
        blockDataDaoConfig.initIdentityScope(type);

        blockLevelDataDaoConfig = daoConfigMap.get(BlockLevelDataDao.class).clone();
        blockLevelDataDaoConfig.initIdentityScope(type);

        evaluationMasterLocationDataDaoConfig = daoConfigMap.get(EvaluationMasterLocationDataDao.class).clone();
        evaluationMasterLocationDataDaoConfig.initIdentityScope(type);

        evaluationMasterShgDataDaoConfig = daoConfigMap.get(EvaluationMasterShgDataDao.class).clone();
        evaluationMasterShgDataDaoConfig.initIdentityScope(type);

        evaluationMasterTrainingDataDaoConfig = daoConfigMap.get(EvaluationMasterTrainingDataDao.class).clone();
        evaluationMasterTrainingDataDaoConfig.initIdentityScope(type);

        evaluationSyncDataDaoConfig = daoConfigMap.get(EvaluationSyncDataDao.class).clone();
        evaluationSyncDataDaoConfig.initIdentityScope(type);

        evaluationSyncQuestionDataDaoConfig = daoConfigMap.get(EvaluationSyncQuestionDataDao.class).clone();
        evaluationSyncQuestionDataDaoConfig.initIdentityScope(type);

        evaluationSyncShgDataDaoConfig = daoConfigMap.get(EvaluationSyncShgDataDao.class).clone();
        evaluationSyncShgDataDaoConfig.initIdentityScope(type);

        gpDataDaoConfig = daoConfigMap.get(GpDataDao.class).clone();
        gpDataDaoConfig.initIdentityScope(type);

        loginInfoDaoConfig = daoConfigMap.get(LoginInfoDao.class).clone();
        loginInfoDaoConfig.initIdentityScope(type);

        moduleDataDaoConfig = daoConfigMap.get(ModuleDataDao.class).clone();
        moduleDataDaoConfig.initIdentityScope(type);

        questionInfoDetailDaoConfig = daoConfigMap.get(QuestionInfoDetailDao.class).clone();
        questionInfoDetailDaoConfig.initIdentityScope(type);

        shgDataDaoConfig = daoConfigMap.get(ShgDataDao.class).clone();
        shgDataDaoConfig.initIdentityScope(type);

        shgMemberDataDaoConfig = daoConfigMap.get(ShgMemberDataDao.class).clone();
        shgMemberDataDaoConfig.initIdentityScope(type);

        shgModuleDataDaoConfig = daoConfigMap.get(ShgModuleDataDao.class).clone();
        shgModuleDataDaoConfig.initIdentityScope(type);

        titleInfoDetailDaoConfig = daoConfigMap.get(TitleInfoDetailDao.class).clone();
        titleInfoDetailDaoConfig.initIdentityScope(type);

        trainingInfoDataDaoConfig = daoConfigMap.get(TrainingInfoDataDao.class).clone();
        trainingInfoDataDaoConfig.initIdentityScope(type);

        trainingLocationInfoDaoConfig = daoConfigMap.get(TrainingLocationInfoDao.class).clone();
        trainingLocationInfoDaoConfig.initIdentityScope(type);

        trainingModuleInfoDaoConfig = daoConfigMap.get(TrainingModuleInfoDao.class).clone();
        trainingModuleInfoDaoConfig.initIdentityScope(type);

        trainingShgAndMemberDataDaoConfig = daoConfigMap.get(TrainingShgAndMemberDataDao.class).clone();
        trainingShgAndMemberDataDaoConfig.initIdentityScope(type);

        viewReportDataDaoConfig = daoConfigMap.get(ViewReportDataDao.class).clone();
        viewReportDataDaoConfig.initIdentityScope(type);

        viewReportModuleDataDaoConfig = daoConfigMap.get(ViewReportModuleDataDao.class).clone();
        viewReportModuleDataDaoConfig.initIdentityScope(type);

        viewReportMonthDataDaoConfig = daoConfigMap.get(ViewReportMonthDataDao.class).clone();
        viewReportMonthDataDaoConfig.initIdentityScope(type);

        viewReportTrainingDataDaoConfig = daoConfigMap.get(ViewReportTrainingDataDao.class).clone();
        viewReportTrainingDataDaoConfig.initIdentityScope(type);

        villageDataDaoConfig = daoConfigMap.get(VillageDataDao.class).clone();
        villageDataDaoConfig.initIdentityScope(type);

        webRequestDataDaoConfig = daoConfigMap.get(WebRequestDataDao.class).clone();
        webRequestDataDaoConfig.initIdentityScope(type);

        addedTrainingShgDataDao = new AddedTrainingShgDataDao(addedTrainingShgDataDaoConfig, this);
        addedTrainingShgMemberDataDao = new AddedTrainingShgMemberDataDao(addedTrainingShgMemberDataDaoConfig, this);
        addedTrainingShgModuleDataDao = new AddedTrainingShgModuleDataDao(addedTrainingShgModuleDataDaoConfig, this);
        addedTrainingsDataDao = new AddedTrainingsDataDao(addedTrainingsDataDaoConfig, this);
        baselineSyncDataDao = new BaselineSyncDataDao(baselineSyncDataDaoConfig, this);
        baslineQuestionSyncDataDao = new BaslineQuestionSyncDataDao(baslineQuestionSyncDataDaoConfig, this);
        blockDataDao = new BlockDataDao(blockDataDaoConfig, this);
        blockLevelDataDao = new BlockLevelDataDao(blockLevelDataDaoConfig, this);
        evaluationMasterLocationDataDao = new EvaluationMasterLocationDataDao(evaluationMasterLocationDataDaoConfig, this);
        evaluationMasterShgDataDao = new EvaluationMasterShgDataDao(evaluationMasterShgDataDaoConfig, this);
        evaluationMasterTrainingDataDao = new EvaluationMasterTrainingDataDao(evaluationMasterTrainingDataDaoConfig, this);
        evaluationSyncDataDao = new EvaluationSyncDataDao(evaluationSyncDataDaoConfig, this);
        evaluationSyncQuestionDataDao = new EvaluationSyncQuestionDataDao(evaluationSyncQuestionDataDaoConfig, this);
        evaluationSyncShgDataDao = new EvaluationSyncShgDataDao(evaluationSyncShgDataDaoConfig, this);
        gpDataDao = new GpDataDao(gpDataDaoConfig, this);
        loginInfoDao = new LoginInfoDao(loginInfoDaoConfig, this);
        moduleDataDao = new ModuleDataDao(moduleDataDaoConfig, this);
        questionInfoDetailDao = new QuestionInfoDetailDao(questionInfoDetailDaoConfig, this);
        shgDataDao = new ShgDataDao(shgDataDaoConfig, this);
        shgMemberDataDao = new ShgMemberDataDao(shgMemberDataDaoConfig, this);
        shgModuleDataDao = new ShgModuleDataDao(shgModuleDataDaoConfig, this);
        titleInfoDetailDao = new TitleInfoDetailDao(titleInfoDetailDaoConfig, this);
        trainingInfoDataDao = new TrainingInfoDataDao(trainingInfoDataDaoConfig, this);
        trainingLocationInfoDao = new TrainingLocationInfoDao(trainingLocationInfoDaoConfig, this);
        trainingModuleInfoDao = new TrainingModuleInfoDao(trainingModuleInfoDaoConfig, this);
        trainingShgAndMemberDataDao = new TrainingShgAndMemberDataDao(trainingShgAndMemberDataDaoConfig, this);
        viewReportDataDao = new ViewReportDataDao(viewReportDataDaoConfig, this);
        viewReportModuleDataDao = new ViewReportModuleDataDao(viewReportModuleDataDaoConfig, this);
        viewReportMonthDataDao = new ViewReportMonthDataDao(viewReportMonthDataDaoConfig, this);
        viewReportTrainingDataDao = new ViewReportTrainingDataDao(viewReportTrainingDataDaoConfig, this);
        villageDataDao = new VillageDataDao(villageDataDaoConfig, this);
        webRequestDataDao = new WebRequestDataDao(webRequestDataDaoConfig, this);

        registerDao(AddedTrainingShgData.class, addedTrainingShgDataDao);
        registerDao(AddedTrainingShgMemberData.class, addedTrainingShgMemberDataDao);
        registerDao(AddedTrainingShgModuleData.class, addedTrainingShgModuleDataDao);
        registerDao(AddedTrainingsData.class, addedTrainingsDataDao);
        registerDao(BaselineSyncData.class, baselineSyncDataDao);
        registerDao(BaslineQuestionSyncData.class, baslineQuestionSyncDataDao);
        registerDao(BlockData.class, blockDataDao);
        registerDao(BlockLevelData.class, blockLevelDataDao);
        registerDao(EvaluationMasterLocationData.class, evaluationMasterLocationDataDao);
        registerDao(EvaluationMasterShgData.class, evaluationMasterShgDataDao);
        registerDao(EvaluationMasterTrainingData.class, evaluationMasterTrainingDataDao);
        registerDao(EvaluationSyncData.class, evaluationSyncDataDao);
        registerDao(EvaluationSyncQuestionData.class, evaluationSyncQuestionDataDao);
        registerDao(EvaluationSyncShgData.class, evaluationSyncShgDataDao);
        registerDao(GpData.class, gpDataDao);
        registerDao(LoginInfo.class, loginInfoDao);
        registerDao(ModuleData.class, moduleDataDao);
        registerDao(QuestionInfoDetail.class, questionInfoDetailDao);
        registerDao(ShgData.class, shgDataDao);
        registerDao(ShgMemberData.class, shgMemberDataDao);
        registerDao(ShgModuleData.class, shgModuleDataDao);
        registerDao(TitleInfoDetail.class, titleInfoDetailDao);
        registerDao(TrainingInfoData.class, trainingInfoDataDao);
        registerDao(TrainingLocationInfo.class, trainingLocationInfoDao);
        registerDao(TrainingModuleInfo.class, trainingModuleInfoDao);
        registerDao(TrainingShgAndMemberData.class, trainingShgAndMemberDataDao);
        registerDao(ViewReportData.class, viewReportDataDao);
        registerDao(ViewReportModuleData.class, viewReportModuleDataDao);
        registerDao(ViewReportMonthData.class, viewReportMonthDataDao);
        registerDao(ViewReportTrainingData.class, viewReportTrainingDataDao);
        registerDao(VillageData.class, villageDataDao);
        registerDao(WebRequestData.class, webRequestDataDao);
    }
    
    public void clear() {
        addedTrainingShgDataDaoConfig.clearIdentityScope();
        addedTrainingShgMemberDataDaoConfig.clearIdentityScope();
        addedTrainingShgModuleDataDaoConfig.clearIdentityScope();
        addedTrainingsDataDaoConfig.clearIdentityScope();
        baselineSyncDataDaoConfig.clearIdentityScope();
        baslineQuestionSyncDataDaoConfig.clearIdentityScope();
        blockDataDaoConfig.clearIdentityScope();
        blockLevelDataDaoConfig.clearIdentityScope();
        evaluationMasterLocationDataDaoConfig.clearIdentityScope();
        evaluationMasterShgDataDaoConfig.clearIdentityScope();
        evaluationMasterTrainingDataDaoConfig.clearIdentityScope();
        evaluationSyncDataDaoConfig.clearIdentityScope();
        evaluationSyncQuestionDataDaoConfig.clearIdentityScope();
        evaluationSyncShgDataDaoConfig.clearIdentityScope();
        gpDataDaoConfig.clearIdentityScope();
        loginInfoDaoConfig.clearIdentityScope();
        moduleDataDaoConfig.clearIdentityScope();
        questionInfoDetailDaoConfig.clearIdentityScope();
        shgDataDaoConfig.clearIdentityScope();
        shgMemberDataDaoConfig.clearIdentityScope();
        shgModuleDataDaoConfig.clearIdentityScope();
        titleInfoDetailDaoConfig.clearIdentityScope();
        trainingInfoDataDaoConfig.clearIdentityScope();
        trainingLocationInfoDaoConfig.clearIdentityScope();
        trainingModuleInfoDaoConfig.clearIdentityScope();
        trainingShgAndMemberDataDaoConfig.clearIdentityScope();
        viewReportDataDaoConfig.clearIdentityScope();
        viewReportModuleDataDaoConfig.clearIdentityScope();
        viewReportMonthDataDaoConfig.clearIdentityScope();
        viewReportTrainingDataDaoConfig.clearIdentityScope();
        villageDataDaoConfig.clearIdentityScope();
        webRequestDataDaoConfig.clearIdentityScope();
    }

    public AddedTrainingShgDataDao getAddedTrainingShgDataDao() {
        return addedTrainingShgDataDao;
    }

    public AddedTrainingShgMemberDataDao getAddedTrainingShgMemberDataDao() {
        return addedTrainingShgMemberDataDao;
    }

    public AddedTrainingShgModuleDataDao getAddedTrainingShgModuleDataDao() {
        return addedTrainingShgModuleDataDao;
    }

    public AddedTrainingsDataDao getAddedTrainingsDataDao() {
        return addedTrainingsDataDao;
    }

    public BaselineSyncDataDao getBaselineSyncDataDao() {
        return baselineSyncDataDao;
    }

    public BaslineQuestionSyncDataDao getBaslineQuestionSyncDataDao() {
        return baslineQuestionSyncDataDao;
    }

    public BlockDataDao getBlockDataDao() {
        return blockDataDao;
    }

    public BlockLevelDataDao getBlockLevelDataDao() {
        return blockLevelDataDao;
    }

    public EvaluationMasterLocationDataDao getEvaluationMasterLocationDataDao() {
        return evaluationMasterLocationDataDao;
    }

    public EvaluationMasterShgDataDao getEvaluationMasterShgDataDao() {
        return evaluationMasterShgDataDao;
    }

    public EvaluationMasterTrainingDataDao getEvaluationMasterTrainingDataDao() {
        return evaluationMasterTrainingDataDao;
    }

    public EvaluationSyncDataDao getEvaluationSyncDataDao() {
        return evaluationSyncDataDao;
    }

    public EvaluationSyncQuestionDataDao getEvaluationSyncQuestionDataDao() {
        return evaluationSyncQuestionDataDao;
    }

    public EvaluationSyncShgDataDao getEvaluationSyncShgDataDao() {
        return evaluationSyncShgDataDao;
    }

    public GpDataDao getGpDataDao() {
        return gpDataDao;
    }

    public LoginInfoDao getLoginInfoDao() {
        return loginInfoDao;
    }

    public ModuleDataDao getModuleDataDao() {
        return moduleDataDao;
    }

    public QuestionInfoDetailDao getQuestionInfoDetailDao() {
        return questionInfoDetailDao;
    }

    public ShgDataDao getShgDataDao() {
        return shgDataDao;
    }

    public ShgMemberDataDao getShgMemberDataDao() {
        return shgMemberDataDao;
    }

    public ShgModuleDataDao getShgModuleDataDao() {
        return shgModuleDataDao;
    }

    public TitleInfoDetailDao getTitleInfoDetailDao() {
        return titleInfoDetailDao;
    }

    public TrainingInfoDataDao getTrainingInfoDataDao() {
        return trainingInfoDataDao;
    }

    public TrainingLocationInfoDao getTrainingLocationInfoDao() {
        return trainingLocationInfoDao;
    }

    public TrainingModuleInfoDao getTrainingModuleInfoDao() {
        return trainingModuleInfoDao;
    }

    public TrainingShgAndMemberDataDao getTrainingShgAndMemberDataDao() {
        return trainingShgAndMemberDataDao;
    }

    public ViewReportDataDao getViewReportDataDao() {
        return viewReportDataDao;
    }

    public ViewReportModuleDataDao getViewReportModuleDataDao() {
        return viewReportModuleDataDao;
    }

    public ViewReportMonthDataDao getViewReportMonthDataDao() {
        return viewReportMonthDataDao;
    }

    public ViewReportTrainingDataDao getViewReportTrainingDataDao() {
        return viewReportTrainingDataDao;
    }

    public VillageDataDao getVillageDataDao() {
        return villageDataDao;
    }

    public WebRequestDataDao getWebRequestDataDao() {
        return webRequestDataDao;
    }

}
