package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EVALUATION_SYNC_QUESTION_DATA".
*/
public class EvaluationSyncQuestionDataDao extends AbstractDao<EvaluationSyncQuestionData, Long> {

    public static final String TABLENAME = "EVALUATION_SYNC_QUESTION_DATA";

    /**
     * Properties of entity EvaluationSyncQuestionData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TrainingId = new Property(1, String.class, "trainingId", false, "TRAINING_ID");
        public final static Property ShgCode = new Property(2, String.class, "shgCode", false, "SHG_CODE");
        public final static Property QuestionCode = new Property(3, String.class, "questionCode", false, "QUESTION_CODE");
        public final static Property AnswerValue = new Property(4, String.class, "answerValue", false, "ANSWER_VALUE");
        public final static Property EvaluationSyncStatus = new Property(5, String.class, "evaluationSyncStatus", false, "EVALUATION_SYNC_STATUS");
    }


    public EvaluationSyncQuestionDataDao(DaoConfig config) {
        super(config);
    }
    
    public EvaluationSyncQuestionDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EVALUATION_SYNC_QUESTION_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TRAINING_ID\" TEXT," + // 1: trainingId
                "\"SHG_CODE\" TEXT," + // 2: shgCode
                "\"QUESTION_CODE\" TEXT," + // 3: questionCode
                "\"ANSWER_VALUE\" TEXT," + // 4: answerValue
                "\"EVALUATION_SYNC_STATUS\" TEXT);"); // 5: evaluationSyncStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EVALUATION_SYNC_QUESTION_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EvaluationSyncQuestionData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String questionCode = entity.getQuestionCode();
        if (questionCode != null) {
            stmt.bindString(4, questionCode);
        }
 
        String answerValue = entity.getAnswerValue();
        if (answerValue != null) {
            stmt.bindString(5, answerValue);
        }
 
        String evaluationSyncStatus = entity.getEvaluationSyncStatus();
        if (evaluationSyncStatus != null) {
            stmt.bindString(6, evaluationSyncStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EvaluationSyncQuestionData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String trainingId = entity.getTrainingId();
        if (trainingId != null) {
            stmt.bindString(2, trainingId);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String questionCode = entity.getQuestionCode();
        if (questionCode != null) {
            stmt.bindString(4, questionCode);
        }
 
        String answerValue = entity.getAnswerValue();
        if (answerValue != null) {
            stmt.bindString(5, answerValue);
        }
 
        String evaluationSyncStatus = entity.getEvaluationSyncStatus();
        if (evaluationSyncStatus != null) {
            stmt.bindString(6, evaluationSyncStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EvaluationSyncQuestionData readEntity(Cursor cursor, int offset) {
        EvaluationSyncQuestionData entity = new EvaluationSyncQuestionData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // trainingId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // questionCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // answerValue
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // evaluationSyncStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EvaluationSyncQuestionData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTrainingId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQuestionCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAnswerValue(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEvaluationSyncStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EvaluationSyncQuestionData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EvaluationSyncQuestionData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EvaluationSyncQuestionData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
