package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHG_DATA".
*/
public class ShgDataDao extends AbstractDao<ShgData, Long> {

    public static final String TABLENAME = "SHG_DATA";

    /**
     * Properties of entity ShgData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShgCode = new Property(1, String.class, "shgCode", false, "SHG_CODE");
        public final static Property ShgName = new Property(2, String.class, "shgName", false, "SHG_NAME");
        public final static Property VillageCode = new Property(3, String.class, "villageCode", false, "VILLAGE_CODE");
        public final static Property BaselineStatus = new Property(4, String.class, "baselineStatus", false, "BASELINE_STATUS");
        public final static Property VillageStatus = new Property(5, String.class, "villageStatus", false, "VILLAGE_STATUS");
    }


    public ShgDataDao(DaoConfig config) {
        super(config);
    }
    
    public ShgDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHG_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHG_CODE\" TEXT," + // 1: shgCode
                "\"SHG_NAME\" TEXT," + // 2: shgName
                "\"VILLAGE_CODE\" TEXT," + // 3: villageCode
                "\"BASELINE_STATUS\" TEXT," + // 4: baselineStatus
                "\"VILLAGE_STATUS\" TEXT);"); // 5: villageStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHG_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShgData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String shgName = entity.getShgName();
        if (shgName != null) {
            stmt.bindString(3, shgName);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(4, villageCode);
        }
 
        String baselineStatus = entity.getBaselineStatus();
        if (baselineStatus != null) {
            stmt.bindString(5, baselineStatus);
        }
 
        String villageStatus = entity.getVillageStatus();
        if (villageStatus != null) {
            stmt.bindString(6, villageStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShgData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String shgName = entity.getShgName();
        if (shgName != null) {
            stmt.bindString(3, shgName);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(4, villageCode);
        }
 
        String baselineStatus = entity.getBaselineStatus();
        if (baselineStatus != null) {
            stmt.bindString(5, baselineStatus);
        }
 
        String villageStatus = entity.getVillageStatus();
        if (villageStatus != null) {
            stmt.bindString(6, villageStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ShgData readEntity(Cursor cursor, int offset) {
        ShgData entity = new ShgData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shgCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // villageCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // baselineStatus
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // villageStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShgData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShgCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVillageCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBaselineStatus(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVillageStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShgData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShgData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShgData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
