package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIEW_REPORT_DATA".
*/
public class ViewReportDataDao extends AbstractDao<ViewReportData, Long> {

    public static final String TABLENAME = "VIEW_REPORT_DATA";

    /**
     * Properties of entity ViewReportData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MonthCode = new Property(1, String.class, "monthCode", false, "MONTH_CODE");
        public final static Property Year = new Property(2, String.class, "year", false, "YEAR");
        public final static Property BaselineDone = new Property(3, String.class, "baselineDone", false, "BASELINE_DONE");
        public final static Property EvaluationDone = new Property(4, String.class, "evaluationDone", false, "EVALUATION_DONE");
        public final static Property ShgUniquelyDone = new Property(5, String.class, "shgUniquelyDone", false, "SHG_UNIQUELY_DONE");
    }


    public ViewReportDataDao(DaoConfig config) {
        super(config);
    }
    
    public ViewReportDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIEW_REPORT_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MONTH_CODE\" TEXT," + // 1: monthCode
                "\"YEAR\" TEXT," + // 2: year
                "\"BASELINE_DONE\" TEXT," + // 3: baselineDone
                "\"EVALUATION_DONE\" TEXT," + // 4: evaluationDone
                "\"SHG_UNIQUELY_DONE\" TEXT);"); // 5: shgUniquelyDone
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIEW_REPORT_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ViewReportData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String monthCode = entity.getMonthCode();
        if (monthCode != null) {
            stmt.bindString(2, monthCode);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(3, year);
        }
 
        String baselineDone = entity.getBaselineDone();
        if (baselineDone != null) {
            stmt.bindString(4, baselineDone);
        }
 
        String evaluationDone = entity.getEvaluationDone();
        if (evaluationDone != null) {
            stmt.bindString(5, evaluationDone);
        }
 
        String shgUniquelyDone = entity.getShgUniquelyDone();
        if (shgUniquelyDone != null) {
            stmt.bindString(6, shgUniquelyDone);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ViewReportData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String monthCode = entity.getMonthCode();
        if (monthCode != null) {
            stmt.bindString(2, monthCode);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(3, year);
        }
 
        String baselineDone = entity.getBaselineDone();
        if (baselineDone != null) {
            stmt.bindString(4, baselineDone);
        }
 
        String evaluationDone = entity.getEvaluationDone();
        if (evaluationDone != null) {
            stmt.bindString(5, evaluationDone);
        }
 
        String shgUniquelyDone = entity.getShgUniquelyDone();
        if (shgUniquelyDone != null) {
            stmt.bindString(6, shgUniquelyDone);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ViewReportData readEntity(Cursor cursor, int offset) {
        ViewReportData entity = new ViewReportData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // monthCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // year
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // baselineDone
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // evaluationDone
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // shgUniquelyDone
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ViewReportData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonthCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYear(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBaselineDone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEvaluationDone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setShgUniquelyDone(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ViewReportData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ViewReportData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ViewReportData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
