package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIEW_REPORT_MONTH_DATA".
*/
public class ViewReportMonthDataDao extends AbstractDao<ViewReportMonthData, Long> {

    public static final String TABLENAME = "VIEW_REPORT_MONTH_DATA";

    /**
     * Properties of entity ViewReportMonthData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MonthCode = new Property(1, String.class, "monthCode", false, "MONTH_CODE");
        public final static Property Year = new Property(2, String.class, "year", false, "YEAR");
        public final static Property WorkingDays = new Property(3, String.class, "workingDays", false, "WORKING_DAYS");
    }


    public ViewReportMonthDataDao(DaoConfig config) {
        super(config);
    }
    
    public ViewReportMonthDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIEW_REPORT_MONTH_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MONTH_CODE\" TEXT," + // 1: monthCode
                "\"YEAR\" TEXT," + // 2: year
                "\"WORKING_DAYS\" TEXT);"); // 3: workingDays
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIEW_REPORT_MONTH_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ViewReportMonthData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String monthCode = entity.getMonthCode();
        if (monthCode != null) {
            stmt.bindString(2, monthCode);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(3, year);
        }
 
        String workingDays = entity.getWorkingDays();
        if (workingDays != null) {
            stmt.bindString(4, workingDays);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ViewReportMonthData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String monthCode = entity.getMonthCode();
        if (monthCode != null) {
            stmt.bindString(2, monthCode);
        }
 
        String year = entity.getYear();
        if (year != null) {
            stmt.bindString(3, year);
        }
 
        String workingDays = entity.getWorkingDays();
        if (workingDays != null) {
            stmt.bindString(4, workingDays);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ViewReportMonthData readEntity(Cursor cursor, int offset) {
        ViewReportMonthData entity = new ViewReportMonthData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // monthCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // year
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // workingDays
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ViewReportMonthData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMonthCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setYear(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWorkingDays(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ViewReportMonthData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ViewReportMonthData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ViewReportMonthData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
