package com.shaksham.model.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WEB_REQUEST_DATA".
*/
public class WebRequestDataDao extends AbstractDao<WebRequestData, Void> {

    public static final String TABLENAME = "WEB_REQUEST_DATA";

    /**
     * Properties of entity WebRequestData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property VillageCode = new Property(0, String.class, "villageCode", false, "VILLAGE_CODE");
        public final static Property Status = new Property(1, String.class, "status", false, "STATUS");
    }


    public WebRequestDataDao(DaoConfig config) {
        super(config);
    }
    
    public WebRequestDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEB_REQUEST_DATA\" (" + //
                "\"VILLAGE_CODE\" TEXT," + // 0: villageCode
                "\"STATUS\" TEXT);"); // 1: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEB_REQUEST_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WebRequestData entity) {
        stmt.clearBindings();
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(1, villageCode);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(2, status);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WebRequestData entity) {
        stmt.clearBindings();
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(1, villageCode);
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(2, status);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public WebRequestData readEntity(Cursor cursor, int offset) {
        WebRequestData entity = new WebRequestData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // villageCode
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WebRequestData entity, int offset) {
        entity.setVillageCode(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStatus(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(WebRequestData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(WebRequestData entity) {
        return null;
    }

    @Override
    public boolean hasKey(WebRequestData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
